
[build]
target = "x86_64-os.json"

# The target.'cfg(target_os = "none")' table applies to all targets that have
# set the "os" field of their target configuration file to "none"
# The runner key specifies the command that should be invoked for cargo run
[target.'cfg(target_os="none")']
runner = "bootimage runner"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]